sudo: required
services:
  - docker

before_install:
  - docker build -t mbox353/frontend -f Dockerfile.dev .

script:
  - docker run mbox353/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "My First Elastic Beanstalk Application"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-646844516110"
  bucket_path: "My First Elastic Beanstalk Application"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"